### ISSUE TITLE
Error - MS Rewards page has changed

### ISSUE THREAD

**Issue by E-v-o** [tmxkn1/Microsoft-Reward-Chrome-Ext#1]
Hi there, I'm getting an error notification stating the rewards page has updated, are there any plans to update the extension as it would be great to speed up the daily reward cycle.

**Comment by tmxkn1** [comment]
This is a bug rather than a real error. Normally it is caused by being signed out from Microsoft account. Just click the icon -> Microsoft Reward and login to your account. Then click the icon again -> Check Now.

I don't have time to fix the issue. Unless it is completely broken, I don't feel like to fix it. Sorry.
