### ISSUE TITLE
Broken After Updating

### ISSUE THREAD

**Issue by OcciZio** [tmxkn1/Microsoft-Reward-Chrome-Ext#115]
**Describe the bug**
Ever since updating to the new V2.24.2.1 version, when interacting with the extension it no longer opens the page to the "Challenge" and some of them arnt being completed after i do them. 

**Since when**
04/15/2023

**Screenshots**
there are no error codes

**Your country**
USA

**Your web browser and OS**
Chrome

**Additional context**
The instances where the challenge isnt completed eventually goes through after afew tries but being able to open the web page by clicking on the extension never worked since the update

**Comment by d6hlkgoczv** [comment]
It's happening with me too. My solution was left clicking and right clicking it many times until the context menu for 'open in new tab' appears.

**Comment by LittleBigMan81** [comment]
I have tried both the previous version (2.24.1.1) and the new version (2.24.1.2) neither are working with the Edge browser

**Comment by ninjatall12** [comment]
> It's happening with me too. My solution was left clicking and right clicking it many times until the context menu for 'open in new tab' appears.

holding ctrl+ spam left click works aswell

**Comment by LittleBigMan81** [comment]
I have tried both the previous version (2.24.1.1) and the new version (2.24.1.2) neither are working with the Edge browser.

Update: I also tried 2.24.2.1 after discovering I didn't have the latest release, and it does seem to be working so far. I'll give an update if it doesn't work when I switch to my alternate accounts.

**Comment by OcciZio** [comment]
for now i just downgraded to version V2.24.1.2 ant that fixed the issue but it stopped doing the automatic searches. ill see if i can find a working version.

**Comment by LittleBigMan81** [comment]
Update 2: It's not working at all (2.24.2.1) now.

I have tried both the previous version (2.24.1.1) and the new version (2.24.1.2) neither are working with the Edge browser.

Update: I also tried 2.24.2.1 after discovering I didn't have the latest release, and it does seem to be working so far. I'll give an update if it doesn't work when I switch to my alternate accounts.

**Comment by tmxkn1** [comment]
There isn't any way I can make this work, as the problem is on the Microsoft side, which isn't technically a bug but a design change, and I have no way to modify it. 

**The only solution is to hold down control and click the link.**

Technical explanation:
The pop-up page is an `iframe` object which opens the same `iframe` page as you click the reward badge on www.bing.com. The links in the pop-up page are coded to open in the current tab rather than a new tab. Since the pop-up page of an extension cannot be reloaded, the link will not be open. But if you control click, it can open in a new tab. Furthermore, `iframe` contents cannot be modified locally, so I cannot change the behaviour of the links.
