### ISSUE TITLE
Enhancement: Get quiz answers

### ISSUE THREAD

**Issue by RannyBergamotte** [tmxkn1/Microsoft-Reward-Chrome-Ext#32]
I know that obviously you have said that you won't make the quiz automated, but a possible time-saving workaround is in the pop-up of the extension, when working on a quiz, get the quiz answers from r/MicrosoftRewards so that there is no need to switch between tabs, and you can easily/mindlessly just put in answers based on what the extensions tells you to do.

**Comment by tmxkn1** [comment]
This would require more active maintenance as answers from Reddit are community based. Consistency in post contents is not guaranteed. It would become a nightmare to keep track of the changes and update the extension accordingly. I think it is also easier for you to place two web browser windows side by side rather than clicking  the extension for each every question?
