### ISSUE TITLE
Repeat Errors

### ISSUE THREAD

**Issue by LiothGold** [tmxkn1/Microsoft-Reward-Chrome-Ext#80]
The latest version seems to have totally ceased functioning as of the 11/1/2022

**Comment by Los-3r** [comment]
I'm having this issue as well.

**Comment by ceticdev** [comment]
Same here, had to attempt to use one of the Selenium bots and those are a nightmare. Please do another hotfix for anything that may have broken since May! <3

**Comment by ceticdev** [comment]
I completely reinstalled the extension and any issues I saw seem to be gone. Since all my tasks were completed by another bot, I will update on whether or not the extension is still not completing tasks.

Still would be nice to see an update, I'm sure Microsoft changes things every once in awhile to detect bots and this hasn't been updated since May.

**Comment by 666dsa666** [comment]
Well there is no need for an update atm so unless things break or before 2023 (and maniffest v3) I believe there won't be any.

**Comment by ceticdev** [comment]
Sounds good. A reinstall did fix everything. Not sure what happened. Looking forward to manifest v3

**Comment by LordHades27** [comment]
The extension seems to have stopped working for me as well, even with multiple reinstalls, nothing seems to be helping.

**Comment by tmxkn1** [comment]
If you are still experiencing the problem, please open a new issue with more detailed descriptions and screenshots of the errors.
